#!/bin/bash

#Ciel ulohy je zobrat N cele cislo 1,2,3..
#Zystit rozdiel medzi (1^2+2^2+3^2..) vs (1+2+3..)^2

usernum=0
tot1=0
tot2=0


read -p "enter the number" usernum

for (( i=0; i<usernum; i++)); do
    tot1=$((usernum ** 2 + tot1))
    tot2=$((usernum + tot2))
    echo "Case 1: {$tot1} & Case 2: {$tot}"
done

echo "The first case is: {$tot1}"
tot2=(($tot2 ** 2))
echo "The second case is {$tot2}"



