#!/bin/bash

#zadanie je identifikovat a najst rozdiel a ukazat ho v podobnych textoch

read -p "Strand 1: " strand1
read -p "Strand 2: " strand2

difference=""

if ((${#strand1}==${#strand2})); then
    for ((i=0 ; i<=${#strand1}; i++)); do
        if [[${strand1:i:1} == ${strand2:i:1}]]; then
            $difference+=" "
            
        else
            $difference+="^"
        fi
    done
else 
    echo "Strands are not equal in lenght!!"
fi

echo -e "$strand1/n$strand2/n$difference"
#or just print them separately and hope they align
